### ISSUE TITLE
Add My Bio!

### ISSUE THREAD

**Issue by grodrigu** [githubteacher/developers-june-part1#49]
@githubteacher Please add <b>George Rodriguez</b> to the Bio section

<h3>:thumbsup::thumbsup: Do it! :thumbsup::thumbsup:</h3>

**Comment by grodrigu** [comment]
@arturom-uci Can you fix my :poop:issue:poop:?

**Comment by arturom-uci** [comment]
@grodrigu Mr. :8ball: says there is no help for what you have....
