### ISSUE TITLE
GitHub Teacher Bio missing

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/developers-june-part1#56]
This project needs to include a file that adds the @githubteacher's information.
## Example Bio
- Name: GitHub Sample Teacher
- Occupation: Teacher
- Organization: GitHub
- Favorite Meal: Breakfast

@crichID does this sound like a good contribution?

**Comment by kirananto** [comment]
great

**Comment by crichID** [comment]
@githubteacher this looks great! :+1:

**Comment by rfriedel** [comment]
:+1:

**Comment by githubteacher** [comment]
Going to close this automatically from the pull request ( #89 )in a few moments

**Comment by fubwar1** [comment]
Add me
